[default]
grpc_url = "grpcs://grpcb.in:9001/addsvc.Add"
base_url = 'https://api.github.com'

[alternative]
base_url = 'https://api.github.com'
grpc_url = "grpcs://grpcb.in:9001/addsvc.Add"

[[label]]
value = "bug"
name = "bug"

[[label]]
value = "documentation"
name = "documentation"

[[label]]
value = "duplicate"
name = "duplicate"

[[label]]
value = "enhancement"
name = "enhancement"
